In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

<a href="https://colab.research.google.com/github/lmoroney/dlaicourse/blob/master/TensorFlow%20In%20Practice/Course%203%20-%20NLP/Course%203%20-%20Week%201%20-%20Lesson%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Copyright 2019 The TensorFlow Authors.

In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

In [ ]:
import tensorflow as tf
from tensorflow import keras

from tf.keras.preprocessing.text import Tokenizer
from tf.keras.preprocessing.sequence import pad_sequences

sentences = [
    'I love my dog',
    'I love my cat',
    'You love my dog!',
    'Do you think my dog is amazing?'
]

tokenizer = Tokenizer(num_words = 100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequences, maxlen=5)
print("\nWord Index = " , word_index)
print("\nSequences = " , sequences)
print("\nPadded Sequences:")
print(padded)


# Try with words that the tokenizer wasn't fit to
test_data = [
    'i really love my dog',
    'my dog loves my manatee'
]

test_seq = tokenizer.texts_to_sequences(test_data)
print("\nTest Sequence = ", test_seq)

padded = pad_sequences(test_seq, maxlen=10)
print("\nPadded Test Sequence: ")
print(padded)

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [8]:
sentences = ['I just want to test.',
             'But, i found the answer here!',
             "let's see what's going on...",
             'no! nothing special there.',
             'Okay, then. I am making a longer sentence in the last sentence.']

tokenizer = Tokenizer(num_words=50, lower=False, oov_token='<OOV>')
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)

padded = pad_sequences(sequences, padding='post') #, maxlen=8, truncating='post')

print("\nWord Index = " , word_index)
print("\nSequences = " , sequences)
print("\nPadded Sequences:")
print(padded)


Word Index =  {'<OOV>': 1, 'I': 2, 'the': 3, 'sentence': 4, 'just': 5, 'want': 6, 'to': 7, 'test': 8, 'But': 9, 'i': 10, 'found': 11, 'answer': 12, 'here': 13, "let's": 14, 'see': 15, "what's": 16, 'going': 17, 'on': 18, 'no': 19, 'nothing': 20, 'special': 21, 'there': 22, 'Okay': 23, 'then': 24, 'am': 25, 'making': 26, 'a': 27, 'longer': 28, 'in': 29, 'last': 30}

Sequences =  [[2, 5, 6, 7, 8], [9, 10, 11, 3, 12, 13], [14, 15, 16, 17, 18], [19, 20, 21, 22], [23, 24, 2, 25, 26, 27, 28, 4, 29, 3, 30, 4]]

Padded Sequences:
[[ 2  5  6  7  8  0  0  0  0  0  0  0]
 [ 9 10 11  3 12 13  0  0  0  0  0  0]
 [14 15 16 17 18  0  0  0  0  0  0  0]
 [19 20 21 22  0  0  0  0  0  0  0  0]
 [23 24  2 25 26 27 28  4 29  3 30  4]]


In [10]:
# Try with words that the tokenizer wasn't fit to
test_data = [
    'i really love my dog',
    'my dog loves my manatee there']

test_text = tokenizer.texts_to_sequences(test_data)
print("\nTest Sequence = ", test_text)

padded = pad_sequences(test_text, padding='post') #, maxlen=3, truncating='post')
print("\nPadded Test Sequence: ")
print(padded)


Test Sequence =  [[10, 1, 1, 1, 1], [1, 1, 1, 1, 1, 22]]

Padded Test Sequence: 
[[10  1  1  1  1  0]
 [ 1  1  1  1  1 22]]
